/* Generated By:JavaCC: Do not edit this line. RegexConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RegexConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAREN = 1;
  /** RegularExpression Id. */
  int RPAREN = 2;
  /** RegularExpression Id. */
  int OR = 3;
  /** RegularExpression Id. */
  int STAR = 4;
  /** RegularExpression Id. */
  int CONSUMED = 5;
  /** RegularExpression Id. */
  int RULE = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\"|\"",
    "\"*\"",
    "<CONSUMED>",
    "<RULE>",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"}\"",
  };

}
